plugins { id 'com.android.application' version '8.7.3' }
android {
 namespace 'com.local.pickup'
 compileSdk 35
 defaultConfig { applicationId 'com.local.pickup'; minSdk 26; targetSdk 34; versionCode 3; versionName '0.2.1' }
 sourceSets { main { manifest.srcFile 'AndroidManifest.xml'; java.srcDirs = ['src']; res.srcDirs = ['res'] } }
 compileOptions { sourceCompatibility JavaVersion.VERSION_1_8; targetCompatibility JavaVersion.VERSION_1_8 }
}
