import com.local.pickup.ImageParcelParser

fun main() {
    var checks = 0
    fun expect(value: Boolean, message: String) { check(value) { message }; checks++ }
    fun scan(text: String) = ImageParcelParser.parse(text)
    val screenshot = scan("菜鸟驿站\n快递公司：中通快递\n取件码\n8 - 5 - 5794\n驿站名称：林业大学大活店\n驿站地址：江苏省南京市玄武区龙蟠路159号\n联系电话：13812345678")
    expect(screenshot.parcels.single().code == "8-5-5794", "code on next line")
    expect(screenshot.carrier == "中通快递", "courier wins over station platform")
    expect(screenshot.station == "林业大学大活店 · 江苏省南京市玄武区龙蟠路159号", "name and address")
    expect(!screenshot.station.contains("13812345678"), "phone excluded")
    val fullWidth = scan("取 件 码：３－１－１２９４\n快递公司：圆通速递\n地址：南京市玄武区")
    expect(fullWidth.parcels.single().code == "3-1-1294", "fullwidth and spaced labels")
    expect(fullWidth.carrier == "圆通速递", "fullwidth metadata")
    expect(scan("快递公司：韵达快递\n取件码：A7B29\n地址：西门驿站").parcels.single().code == "A7B29", "letters retained")
    expect(scan("取货码：123456\n地址：南京市\n快递公司：顺丰速运").station == "南京市", "next field excluded")
    expect(scan("地址：南京市 快递公司：极兔速递\n取件码：998811").station == "南京市", "inline next field excluded")
    val sms = scan("【申通快递】快递已到，请凭6328取件，地址：南门驿站。")
    expect(sms.parcels.single().code == "6328", "SMS embedded in screenshot")
    expect(sms.carrier == "申通快递", "courier in SMS")
    expect(scan("取件码：13812345678\n地址：南京市").parcels.isEmpty(), "phone not pickup code")
    expect(scan("物流单号：YT1234567890\n联系电话：13812345678\n地址：南京市").parcels.isEmpty(), "tracking and phone not pickup code")
    expect(scan("银行登录验证码：628193").parcels.isEmpty(), "unrelated verification not parcel")
    expect(scan("").parcels.isEmpty(), "empty image")
    expect(scan("取件码：1234567890123").parcels.isEmpty(), "oversized code rejected")
    expect(scan("取件码：8-5-5/94").parcels.isEmpty(), "uncertain glyph does not silently truncate code")
    val partial = scan("快递公司：京东物流\n驿站地址：南京市栖霞区学林路100号")
    expect(partial.parcels.isEmpty() && partial.carrier == "京东物流" && partial.station.contains("学林路100号"), "partial metadata usable")
    val multiple = scan("中通快递\n取件码：3-1-1294\n地址：北门驿站\n\n圆通速递\n取件码：4-4-4216\n地址：南门驿站")
    expect(multiple.parcels.size == 2, "multiple cards")
    expect(multiple.parcels[0].station == "北门驿站" && multiple.parcels[0].carrier == "中通快递", "first card metadata")
    expect(multiple.parcels[1].station == "南门驿站" && multiple.parcels[1].carrier == "圆通速递", "second card metadata")
    val ambiguous = scan("中通快递\n取件码：111111\n取件码：222222\n地址：北门驿站")
    expect(ambiguous.parcels.all { it.station.isEmpty() && it.carrier == "其他" }, "ambiguous multi-card metadata not guessed")
    expect(scan("取件码：123456\n取件码：123456").parcels.size == 1, "deduplicate code")
    expect(scan("3-1-1294\n林业大学大活店\n圆通速递").parcels.single().code == "3-1-1294", "unlabelled shelf code")
    expect(scan("3-1-1294\n林业大学大活店").station == "林业大学大活店", "unlabelled station")
    expect(scan("2026-10-02\n123456\n13812345678").parcels.isEmpty(), "date and naked numbers excluded")
    val logistics = scan("wg\n\n收货地址\n\n岛号码保护\n\n取件码 7-2-9408\n\n复制 | 分享取件\n\n南城大学生活动中心 | 大学快递服务点 “| 拨打电话\n\n中通快递: 12345678901234\n\n快递员: 张三\n\n快件已送达【代收点-南城大学生活动中心，电话…\n\n收货地址: 江苏省南京市玄武区示例路99号\n\n订单编号: 260925-123456789012345")
    expect(logistics.parcels.single().code == "7-2-9408", "logistics page code excludes tracking and order numbers")
    expect(logistics.parcels.single().carrier == "中通快递", "tracking row supplies carrier across OCR blank blocks")
    expect(logistics.station == "南城大学生活动中心 | 大学快递服务点", "station card excludes call button")
    expect(!logistics.station.contains("号码保护") && !logistics.station.contains("示例路"), "recipient map and home address excluded")
    expect(scan("取件码：123456\n收货地址：南京市玄武区龙蟠路159号").station.isEmpty(), "recipient address is not pickup station")
    expect(scan("取件码：123456\n寄件人地址：上海市浦东新区").station.isEmpty(), "sender address is not pickup station")
    expect(scan("取件码：123456\n收件人地址：南京市\n驿站地址：西门服务点").station == "西门服务点", "explicit pickup address survives recipient address")
    expect(scan("取件码：123456\n地址\n号码保护\n导航\n物流服务").station.isEmpty(), "map actions not station values")
    expect(scan("取件码：123456\n收货地址：南京市\n快件已送达【代收点-北门营业部，电话…").station == "北门营业部", "delivery timeline station without closing bracket")
    expect(scan("取件码：123456\n快件已送达【代收点-北门营业部\n\n电话").station == "北门营业部", "timeline station across sparse OCR blocks")
    expect(scan("圆通速递服务\n取件码：123456\n中通快递：12345678901234").carrier == "中通快递", "tracking evidence beats unrelated courier mention")
    expect(scan("圆通速递\n中通快递\n取件码：123456").carrier == "其他", "conflicting equal carrier evidence needs review")
    expect(scan("菜鸟驿站\n快递公司：韵达快递\n中通快递：12345678901234\n取件码：123456").carrier == "韵达快递", "explicit carrier field has priority")
    expect(scan("圆通速递\n取件码：123456\n\n中通快递：12345678901234").parcels.single().carrier == "中通快递", "single code uses strongest metadata across blocks")
    expect(scan("取件码：123456\n\n物流公司：京东物流\n\n地址：北门驿站").parcels.single().station == "北门驿站", "single code retains separately recognised station")
    expect(scan("取件码：123456\n收货地址\n岛号码保护\n收货地址：南京市").confidence == 0, "excluded map labels do not inflate OCR pass confidence")
    expect(scan("取件码：123456\n中通快递：12345678901234\n地址：北门驿站").confidence > scan("取件码：123456\n圆通速递\n地址：北门驿站").confidence, "OCR result with tracking evidence wins selection")
    val mixed = scan("中通快递\n3-1-1294\n地址：北门驿站\n\n圆通速递\n取件码：4-4-4216\n地址：南门驿站\n\n7-5-3320")
    expect(mixed.parcels.map { it.code } == listOf("3-1-1294", "4-4-4216", "7-5-3320"), "mixed labelled and bare codes retain screenshot order")
    expect(mixed.parcels[0].carrier == "中通快递" && mixed.parcels[1].carrier == "圆通速递", "mixed cards keep their own company")
    expect(scan("取件码：3-1-1294、4-4-4216，7-5-3320").parcels.map { it.code } == listOf("3-1-1294", "4-4-4216", "7-5-3320"), "multiple codes under one label")
    expect(scan("取件码：a7b29\n取件码：A7B29").parcels.size == 1, "case insensitive duplicate code")
    expect(scan("取件码：3-1-1294\n2026-10-09\n12345678901234\n13812345678").parcels.size == 1, "other screenshot numbers excluded from batch")
    println("PASS: $checks image parcel parsing checks")
}
